# This file (dbt_project.yml) is how dbt knows a directory is a dbt project.
# Project names should contain only lowercase characters and underscores.
# By default, dbt looks for the 'dbt_project.yml' in your current working directory and its parents,
# but you can set a different directory using the '--project-dir' flag or the 'DBT_PROJECT_DIR' environment variable.
# Rerefence: https://docs.getdbt.com/reference/dbt_project.yml

name: 'my_dbt_project' # Name is mandatory. 
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_profile' # Make sure this matches the name in profiles.yml

# These configurations specify where dbt should look for different types of files.
model-paths:    ["models"]    # Directories where your models and source files live. Check: https://docs.getdbt.com/reference/project-configs/model-paths
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]       
macro-paths:    ["macros"] 
snapshot-paths: ["snapshots"]

target-path: 'target' # directory which will store compiled SQL files

clean-targets:        # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  my_dbt_project:             # This must match the `name:` config in the beginning of this document.
    bronze:                   # This configures models found in 'dbt_2_transformation/models/bronze'
      +schema: bronze         # This is called 'target schema'. It will override the 'schema:' in profiles.yml
      +materialized: 'table'  # Configured to create tables instead of views
    silver:                   # This configures models found in 'dbt_2_transformation/models/silver'
      +schema: silver         # This is called 'target schema'. It will override the 'schema:' in profiles.yml        
      +materialized: 'table'  # Configured to create tables instead of views
    gold:                     # This configures models found in 'dbt_2_transformation/models/gold'
      +schema: gold           # This is called 'target schema'. It will override the 'schema:' in profiles.yml      
      +materialized: 'table'  # Configured to create tables instead of views